// data.js
// Dữ liệu được chuyển đổi từ file N5_Verbs_Data.csv của bạn.
// Tôi đã thêm các trường `id`, `progress`, và `note` để theo dõi tiến trình học tập.

const n5Verbs = [
  {
    "id": 1,
    "kanji": "行きます",
    "hiragana": "いきます",
    "meaning": "Đi",
    "group": 1,
    "dictionaryForm": "行く",
    "teForm": "行って",
    "naiForm": "行かない",
    "example": "毎日学校へ行きます。(Tôi đi đến trường mỗi ngày)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 2,
    "kanji": "寝ます",
    "hiragana": "ねます",
    "meaning": "Ngủ",
    "group": 2,
    "dictionaryForm": "寝る",
    "teForm": "寝て",
    "naiForm": "寝ない",
    "example": "昨日は早く寝ました。(Hôm qua tôi đã ngủ sớm)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 3,
    "kanji": "働きます",
    "hiragana": "はたらきます",
    "meaning": "Làm việc",
    "group": 1,
    "dictionaryForm": "働く",
    "teForm": "働いて",
    "naiForm": "働かない",
    "example": "父は銀行で働いています。(Bố tôi làm việc ở ngân hàng)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 4,
    "kanji": "終わります",
    "hiragana": "おわります",
    "meaning": "Kết thúc",
    "group": 1,
    "dictionaryForm": "終わる",
    "teForm": "終わって",
    "naiForm": "終わらない",
    "example": "会議は何時に終わりますか。(Cuộc họp kết thúc lúc mấy giờ?)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 5,
    "kanji": "勉強します",
    "hiragana": "べんきょうします",
    "meaning": "Học",
    "group": 3,
    "dictionaryForm": "勉強する",
    "teForm": "勉強して",
    "naiForm": "勉強しない",
    "example": "家で日本語を勉強します。(Tôi học tiếng Nhật ở nhà)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 6,
    "kanji": "します",
    "hiragana": "します",
    "meaning": "Làm",
    "group": 3,
    "dictionaryForm": "する",
    "teForm": "して",
    "naiForm": "しない",
    "example": "週末何をしますか。(Cuối tuần bạn làm gì?)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 7,
    "kanji": "起きます",
    "hiragana": "おきます",
    "meaning": "Thức dậy",
    "group": 2,
    "dictionaryForm": "起きる",
    "teForm": "起きて",
    "naiForm": "起きない",
    "example": "毎朝6時に起きます。(Mỗi sáng tôi thức dậy lúc 6 giờ)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 8,
    "kanji": "来ます",
    "hiragana": "きます",
    "meaning": "Đến",
    "group": 3,
    "dictionaryForm": "来る",
    "teForm": "来て",
    "naiForm": "来ない",
    "example": "友達がうちに遊びに来ます。(Bạn bè đến nhà tôi chơi)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 9,
    "kanji": "帰ります",
    "hiragana": "かえります",
    "meaning": "Về",
    "group": 1,
    "dictionaryForm": "帰る",
    "teForm": "帰って",
    "naiForm": "帰らない",
    "example": "仕事が終わって、うちに帰ります。(Sau khi xong việc, tôi về nhà)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 10,
    "kanji": "食べます",
    "hiragana": "たべます",
    "meaning": "Ăn",
    "group": 2,
    "dictionaryForm": "食べる",
    "teForm": "食べて",
    "naiForm": "食べない",
    "example": "朝ごはんを食べます。(Tôi ăn sáng)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 11,
    "kanji": "飲みます",
    "hiragana": "のみます",
    "meaning": "Uống",
    "group": 1,
    "dictionaryForm": "飲む",
    "teForm": "飲んで",
    "naiForm": "飲まない",
    "example": "コーヒーを飲みます。(Tôi uống cà phê)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 12,
    "kanji": "吸います",
    "hiragana": "すいます",
    "meaning": "Hút (thuốc)",
    "group": 1,
    "dictionaryForm": "吸う",
    "teForm": "吸って",
    "naiForm": "吸わない",
    "example": "たばこを吸います。(Tôi hút thuốc lá)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 13,
    "kanji": "見ます",
    "hiragana": "みます",
    "meaning": "Xem, nhìn",
    "group": 2,
    "dictionaryForm": "見る",
    "teForm": "見て",
    "naiForm": "見ない",
    "example": "テレビを見ます。(Tôi xem tivi)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 14,
    "kanji": "聞きます",
    "hiragana": "ききます",
    "meaning": "Nghe",
    "group": 1,
    "dictionaryForm": "聞く",
    "teForm": "聞いて",
    "naiForm": "聞かない",
    "example": "音楽を聞きます。(Tôi nghe nhạc)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 15,
    "kanji": "読みます",
    "hiragana": "よみます",
    "meaning": "Đọc",
    "group": 1,
    "dictionaryForm": "読む",
    "teForm": "読んで",
    "naiForm": "読まない",
    "example": "本を読みます。(Tôi đọc sách)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 16,
    "kanji": "書きます",
    "hiragana": "かきます",
    "meaning": "Viết, vẽ",
    "group": 1,
    "dictionaryForm": "書く",
    "teForm": "書いて",
    "naiForm": "書かない",
    "example": "手紙を書きます。(Tôi viết thư)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 17,
    "kanji": "買います",
    "hiragana": "かいます",
    "meaning": "Mua",
    "group": 1,
    "dictionaryForm": "買う",
    "teForm": "買って",
    "naiForm": "買わない",
    "example": "新しい靴を買いました。(Tôi đã mua giày mới)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 18,
    "kanji": "撮ります",
    "hiragana": "とります",
    "meaning": "Chụp (ảnh)",
    "group": 1,
    "dictionaryForm": "撮る",
    "teForm": "撮って",
    "naiForm": "撮らない",
    "example": "写真を撮ります。(Tôi chụp ảnh)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 19,
    "kanji": "会います",
    "hiragana": "あいます",
    "meaning": "Gặp",
    "group": 1,
    "dictionaryForm": "会う",
    "teForm": "会って",
    "naiForm": "会わない",
    "example": "友達に会います。(Tôi gặp bạn)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 20,
    "kanji": "切ります",
    "hiragana": "きります",
    "meaning": "Cắt",
    "group": 1,
    "dictionaryForm": "切る",
    "teForm": "切って",
    "naiForm": "切らない",
    "example": "紙を切ります。(Tôi cắt giấy)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 21,
    "kanji": "送ります",
    "hiragana": "おくります",
    "meaning": "Gửi",
    "group": 1,
    "dictionaryForm": "送る",
    "teForm": "送って",
    "naiForm": "送らない",
    "example": "荷物を送ります。(Tôi gửi hành lý)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 22,
    "kanji": "あげます",
    "hiragana": "あげます",
    "meaning": "Cho, tặng",
    "group": 2,
    "dictionaryForm": "あげる",
    "teForm": "あげて",
    "naiForm": "あげない",
    "example": "花をあげます。(Tôi tặng hoa)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 23,
    "kanji": "もらいます",
    "hiragana": "もらいます",
    "meaning": "Nhận",
    "group": 1,
    "dictionaryForm": "もらう",
    "teForm": "もらって",
    "naiForm": "もらわない",
    "example": "プレゼントをもらいました。(Tôi đã nhận được quà)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 24,
    "kanji": "貸します",
    "hiragana": "かします",
    "meaning": "Cho mượn",
    "group": 1,
    "dictionaryForm": "貸す",
    "teForm": "貸して",
    "naiForm": "貸さない",
    "example": "本を貸します。(Tôi cho mượn sách)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 25,
    "kanji": "借ります",
    "hiragana": "かります",
    "meaning": "Mượn",
    "group": 2,
    "dictionaryForm": "借りる",
    "teForm": "借りて",
    "naiForm": "借りない",
    "example": "図書館で本を借ります。(Tôi mượn sách ở thư viện)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 26,
    "kanji": "教えます",
    "hiragana": "おしえます",
    "meaning": "Dạy, cho biết",
    "group": 2,
    "dictionaryForm": "教える",
    "teForm": "教えて",
    "naiForm": "教えない",
    "example": "日本語を教えます。(Tôi dạy tiếng Nhật)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 27,
    "kanji": "習います",
    "hiragana": "ならいます",
    "meaning": "Học (từ ai đó)",
    "group": 1,
    "dictionaryForm": "習う",
    "teForm": "習って",
    "naiForm": "習わない",
    "example": "先生に日本語を習います。(Tôi học tiếng Nhật từ giáo viên)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 28,
    "kanji": "かけます",
    "hiragana": "かけます",
    "meaning": "Gọi (điện thoại)",
    "group": 2,
    "dictionaryForm": "かける",
    "teForm": "かけて",
    "naiForm": "かけない",
    "example": "友達に電話をかけます。(Tôi gọi điện cho bạn)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 29,
    "kanji": "わかります",
    "hiragana": "わかります",
    "meaning": "Hiểu",
    "group": 1,
    "dictionaryForm": "わかる",
    "teForm": "わかって",
    "naiForm": "わからない",
    "example": "日本語が少しわかります。(Tôi hiểu một chút tiếng Nhật)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 30,
    "kanji": "あります",
    "hiragana": "あります",
    "meaning": "Có (đồ vật)",
    "group": 1,
    "dictionaryForm": "ある",
    "teForm": "あって",
    "naiForm": "ない",
    "example": "机の上に本があります。(Trên bàn có quyển sách)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 31,
    "kanji": "います",
    "hiragana": "います",
    "meaning": "Có (người, động vật)",
    "group": 2,
    "dictionaryForm": "いる",
    "teForm": "いて",
    "naiForm": "いない",
    "example": "公園に子供がいます。(Ở công viên có trẻ em)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 32,
    "kanji": "かかります",
    "hiragana": "かかります",
    "meaning": "Mất, tốn (thời gian, tiền)",
    "group": 1,
    "dictionaryForm": "かかる",
    "teForm": "かかって",
    "naiForm": "かからない",
    "example": "駅からうちまで10分かかります。(Từ ga về nhà mất 10 phút)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 33,
    "kanji": "休みます",
    "hiragana": "やすみます",
    "meaning": "Nghỉ ngơi",
    "group": 1,
    "dictionaryForm": "休む",
    "teForm": "休んで",
    "naiForm": "休まない",
    "example": "今日は会社を休みます。(Hôm nay tôi nghỉ làm)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 34,
    "kanji": "遊びます",
    "hiragana": "あそびます",
    "meaning": "Chơi",
    "group": 1,
    "dictionaryForm": "遊ぶ",
    "teForm": "遊んで",
    "naiForm": "遊ばない",
    "example": "公園で遊びます。(Tôi chơi ở công viên)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 35,
    "kanji": "泳ぎます",
    "hiragana": "およぎます",
    "meaning": "Bơi",
    "group": 1,
    "dictionaryForm": "泳ぐ",
    "teForm": "泳いで",
    "naiForm": "泳がない",
    "example": "海で泳ぎます。(Tôi bơi ở biển)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 36,
    "kanji": "迎えます",
    "hiragana": "むかえます",
    "meaning": "Đón",
    "group": 2,
    "dictionaryForm": "迎える",
    "teForm": "迎えて",
    "naiForm": "迎えない",
    "example": "駅で友達を迎えます。(Tôi đón bạn ở ga)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 37,
    "kanji": "疲れます",
    "hiragana": "つかれます",
    "meaning": "Mệt",
    "group": 2,
    "dictionaryForm": "疲れる",
    "teForm": "疲れて",
    "naiForm": "疲れない",
    "example": "仕事で疲れました。(Tôi mệt vì công việc)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 38,
    "kanji": "出します",
    "hiragana": "だします",
    "meaning": "Gửi (thư), Nộp (báo cáo)",
    "group": 1,
    "dictionaryForm": "出す",
    "teForm": "出して",
    "naiForm": "出さない",
    "example": "レポートを出します。(Tôi nộp báo cáo)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 39,
    "kanji": "入ります",
    "hiragana": "はいります",
    "meaning": "Vào",
    "group": 1,
    "dictionaryForm": "入る",
    "teForm": "入って",
    "naiForm": "入らない",
    "example": "喫茶店に入ります。(Tôi vào quán cà phê)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 40,
    "kanji": "出ます",
    "hiragana": "でます",
    "meaning": "Ra, rời khỏi",
    "group": 2,
    "dictionaryForm": "出る",
    "teForm": "出て",
    "naiForm": "出ない",
    "example": "大学を出ます。(Tôi tốt nghiệp đại học)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 41,
    "kanji": "結婚します",
    "hiragana": "けっこんします",
    "meaning": "Kết hôn",
    "group": 3,
    "dictionaryForm": "結婚する",
    "teForm": "結婚して",
    "naiForm": "結婚しない",
    "example": "来年結婚します。(Năm sau tôi sẽ kết hôn)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 42,
    "kanji": "買い物します",
    "hiragana": "かいものします",
    "meaning": "Mua sắm",
    "group": 3,
    "dictionaryForm": "買い物する",
    "teForm": "買い物して",
    "naiForm": "買い物しない",
    "example": "デパートで買い物をします。(Tôi mua sắm ở trung tâm thương mại)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 43,
    "kanji": "食事します",
    "hiragana": "しょくじします",
    "meaning": "Ăn cơm",
    "group": 3,
    "dictionaryForm": "食事する",
    "teForm": "食事して",
    "naiForm": "食事しない",
    "example": "レストランで食事します。(Tôi ăn cơm ở nhà hàng)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 44,
    "kanji": "散歩します",
    "hiragana": "さんぽします",
    "meaning": "Đi dạo",
    "group": 3,
    "dictionaryForm": "散歩する",
    "teForm": "散歩して",
    "naiForm": "散歩しない",
    "example": "公園を散歩します。(Tôi đi dạo ở công viên)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 45,
    "kanji": "つけます",
    "hiragana": "つけます",
    "meaning": "Bật (điện)",
    "group": 2,
    "dictionaryForm": "つける",
    "teForm": "つけて",
    "naiForm": "つけない",
    "example": "電気をつけます。(Tôi bật điện)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 46,
    "kanji": "消します",
    "hiragana": "けします",
    "meaning": "Tắt (điện)",
    "group": 1,
    "dictionaryForm": "消す",
    "teForm": "消して",
    "naiForm": "消さない",
    "example": "テレビを消します。(Tôi tắt tivi)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 47,
    "kanji": "開けます",
    "hiragana": "あけます",
    "meaning": "Mở (cửa)",
    "group": 2,
    "dictionaryForm": "開ける",
    "teForm": "開けて",
    "naiForm": "開けない",
    "example": "ドアを開けます。(Tôi mở cửa)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 48,
    "kanji": "閉めます",
    "hiragana": "しめます",
    "meaning": "Đóng (cửa)",
    "group": 2,
    "dictionaryForm": "閉める",
    "teForm": "閉めて",
    "naiForm": "閉めない",
    "example": "窓を閉めます。(Tôi đóng cửa sổ)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 49,
    "kanji": "急ぎます",
    "hiragana": "いそぎます",
    "meaning": "Vội, gấp",
    "group": 1,
    "dictionaryForm": "急ぐ",
    "teForm": "急いで",
    "naiForm": "急がない",
    "example": "駅へ急ぎます。(Tôi vội đến ga)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 50,
    "kanji": "待ちます",
    "hiragana": "まちます",
    "meaning": "Đợi",
    "group": 1,
    "dictionaryForm": "待つ",
    "teForm": "待って",
    "naiForm": "待たない",
    "example": "バスを待ちます。(Tôi đợi xe buýt)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 51,
    "kanji": "持ちます",
    "hiragana": "もちます",
    "meaning": "Mang, cầm",
    "group": 1,
    "dictionaryForm": "持つ",
    "teForm": "持って",
    "naiForm": "持たない",
    "example": "荷物を持ちます。(Tôi mang hành lý)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 52,
    "kanji": "取ります",
    "hiragana": "とります",
    "meaning": "Lấy",
    "group": 1,
    "dictionaryForm": "取る",
    "teForm": "取って",
    "naiForm": "取らない",
    "example": "塩を取ってください。(Làm ơn lấy giúp tôi muối)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 53,
    "kanji": "手伝います",
    "hiragana": "てつだいます",
    "meaning": "Giúp đỡ",
    "group": 1,
    "dictionaryForm": "手伝う",
    "teForm": "手伝って",
    "naiForm": "手伝わない",
    "example": "母を手伝います。(Tôi giúp mẹ)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 54,
    "kanji": "呼びます",
    "hiragana": "よびます",
    "meaning": "Gọi",
    "group": 1,
    "dictionaryForm": "呼ぶ",
    "teForm": "呼んで",
    "naiForm": "呼ばない",
    "example": "タクシーを呼びます。(Tôi gọi taxi)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 55,
    "kanji": "話します",
    "hiragana": "はなします",
    "meaning": "Nói chuyện",
    "group": 1,
    "dictionaryForm": "話す",
    "teForm": "話して",
    "naiForm": "話さない",
    "example": "友達と話します。(Tôi nói chuyện với bạn)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 56,
    "kanji": "使います",
    "hiragana": "つかいます",
    "meaning": "Sử dụng",
    "group": 1,
    "dictionaryForm": "使う",
    "teForm": "使って",
    "naiForm": "使わない",
    "example": "パソコンを使います。(Tôi sử dụng máy tính)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 57,
    "kanji": "止めます",
    "hiragana": "とめます",
    "meaning": "Dừng, đỗ",
    "group": 2,
    "dictionaryForm": "止める",
    "teForm": "止めて",
    "naiForm": "止めない",
    "example": "ここに車を止めないでください。(Xin đừng đỗ xe ở đây)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 58,
    "kanji": "見せます",
    "hiragana": "みせます",
    "meaning": "Cho xem",
    "group": 2,
    "dictionaryForm": "見せる",
    "teForm": "見せて",
    "naiForm": "見せない",
    "example": "写真を見せます。(Tôi cho xem ảnh)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 59,
    "kanji": "教えます",
    "hiragana": "おしえます",
    "meaning": "Cho biết (địa chỉ)",
    "group": 2,
    "dictionaryForm": "教える",
    "teForm": "教えて",
    "naiForm": "教えない",
    "example": "住所を教えます。(Tôi cho biết địa chỉ)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 60,
    "kanji": "座ります",
    "hiragana": "すわります",
    "meaning": "Ngồi",
    "group": 1,
    "dictionaryForm": "座る",
    "teForm": "座って",
    "naiForm": "座らない",
    "example": "いすに座ります。(Tôi ngồi vào ghế)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 61,
    "kanji": "立ちます",
    "hiragana": "たちます",
    "meaning": "Đứng",
    "group": 1,
    "dictionaryForm": "立つ",
    "teForm": "立って",
    "naiForm": "立たない",
    "example": "ドアの前に立ちます。(Tôi đứng trước cửa)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 62,
    "kanji": "作ります",
    "hiragana": "つくります",
    "meaning": "Làm, chế tạo",
    "group": 1,
    "dictionaryForm": "作る",
    "teForm": "作って",
    "naiForm": "作らない",
    "example": "料理を作ります。(Tôi nấu ăn)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 63,
    "kanji": "売ります",
    "hiragana": "うります",
    "meaning": "Bán",
    "group": 1,
    "dictionaryForm": "売る",
    "teForm": "売って",
    "naiForm": "売らない",
    "example": "古い車を売ります。(Tôi bán xe ô tô cũ)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 64,
    "kanji": "知ります",
    "hiragana": "しります",
    "meaning": "Biết",
    "group": 1,
    "dictionaryForm": "知る",
    "teForm": "知って",
    "naiForm": "知らない",
    "example": "彼の電話番号を知っています。(Tôi biết số điện thoại của anh ấy)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 65,
    "kanji": "住みます",
    "hiragana": "すみます",
    "meaning": "Sống, ở",
    "group": 1,
    "dictionaryForm": "住む",
    "teForm": "住んで",
    "naiForm": "住まない",
    "example": "ハノイに住んでいます。(Tôi đang sống ở Hà Nội)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 66,
    "kanji": "置きます",
    "hiragana": "おきます",
    "meaning": "Đặt, để",
    "group": 1,
    "dictionaryForm": "置く",
    "teForm": "置いて",
    "naiForm": "置かない",
    "example": "机の上に本を置きます。(Tôi đặt sách lên bàn)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 67,
    "kanji": "研究します",
    "hiragana": "けんきゅうします",
    "meaning": "Nghiên cứu",
    "group": 3,
    "dictionaryForm": "研究する",
    "teForm": "研究して",
    "naiForm": "研究しない",
    "example": "大学で経済を研究します。(Tôi nghiên cứu kinh tế ở đại học)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 68,
    "kanji": "乗ります",
    "hiragana": "のります",
    "meaning": "Lên (xe)",
    "group": 1,
    "dictionaryForm": "乗る",
    "teForm": "乗って",
    "naiForm": "乗らない",
    "example": "電車に乗ります。(Tôi lên tàu điện)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 69,
    "kanji": "降ります",
    "hiragana": "おります",
    "meaning": "Xuống (xe)",
    "group": 2,
    "dictionaryForm": "降りる",
    "teForm": "降りて",
    "naiForm": "降りない",
    "example": "次の駅で降ります。(Tôi xuống ở ga tiếp theo)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 70,
    "kanji": "乗り換えます",
    "hiragana": "のりかえます",
    "meaning": "Chuyển (xe)",
    "group": 2,
    "dictionaryForm": "乗り換える",
    "teForm": "乗り換えて",
    "naiForm": "乗り換えない",
    "example": "東京駅で新幹線に乗り換えます。(Tôi chuyển sang tàu Shinkansen ở ga Tokyo)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 71,
    "kanji": "浴びます",
    "hiragana": "あびます",
    "meaning": "Tắm (vòi hoa sen)",
    "group": 2,
    "dictionaryForm": "浴びる",
    "teForm": "浴びて",
    "naiForm": "浴びない",
    "example": "シャワーを浴びます。(Tôi tắm vòi hoa sen)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 72,
    "kanji": "入れます",
    "hiragana": "いれます",
    "meaning": "Cho vào, bỏ vào",
    "group": 2,
    "dictionaryForm": "入れる",
    "teForm": "入れて",
    "naiForm": "入れない",
    "example": "かばんに本を入れます。(Tôi cho sách vào cặp)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 73,
    "kanji": "覚えます",
    "hiragana": "おぼえます",
    "meaning": "Nhớ",
    "group": 2,
    "dictionaryForm": "覚える",
    "teForm": "覚えて",
    "naiForm": "覚えない",
    "example": "新しい言葉を覚えます。(Tôi nhớ từ mới)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 74,
    "kanji": "忘れます",
    "hiragana": "わすれます",
    "meaning": "Quên",
    "group": 2,
    "dictionaryForm": "忘れる",
    "teForm": "忘れて",
    "naiForm": "忘れない",
    "example": "宿題を忘れました。(Tôi đã quên bài tập về nhà)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 75,
    "kanji": "なくします",
    "hiragana": "なくします",
    "meaning": "Làm mất",
    "group": 1,
    "dictionaryForm": "なくす",
    "teForm": "なくして",
    "naiForm": "なくさない",
    "example": "財布をなくしました。(Tôi đã làm mất ví)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 76,
    "kanji": "払います",
    "hiragana": "はらいます",
    "meaning": "Trả tiền",
    "group": 1,
    "dictionaryForm": "払う",
    "teForm": "払って",
    "naiForm": "払わない",
    "example": "カードで払います。(Tôi trả bằng thẻ)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 77,
    "kanji": "返します",
    "hiragana": "かえします",
    "meaning": "Trả lại",
    "group": 1,
    "dictionaryForm": "返す",
    "teForm": "返して",
    "naiForm": "返さない",
    "example": "友達に本を返します。(Tôi trả lại sách cho bạn)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 78,
    "kanji": "出かけます",
    "hiragana": "でかけます",
    "meaning": "Ra ngoài",
    "group": 2,
    "dictionaryForm": "出かける",
    "teForm": "出かけて",
    "naiForm": "出かけない",
    "example": "週末は家族と出かけます。(Cuối tuần tôi ra ngoài cùng gia đình)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 79,
    "kanji": "脱ぎます",
    "hiragana": "ぬぎます",
    "meaning": "Cởi (quần áo, giày)",
    "group": 1,
    "dictionaryForm": "脱ぐ",
    "teForm": "脱いで",
    "naiForm": "脱がない",
    "example": "うちへ帰って、靴を脱ぎます。(Về nhà, tôi cởi giày)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 80,
    "kanji": "持って行きます",
    "hiragana": "もっていきます",
    "meaning": "Mang đi",
    "group": 1,
    "dictionaryForm": "持って行く",
    "teForm": "持って行って",
    "naiForm": "持って行かない",
    "example": "お弁当を持って行きます。(Tôi mang cơm hộp đi)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 81,
    "kanji": "持って来ます",
    "hiragana": "もってきます",
    "meaning": "Mang đến",
    "group": 3,
    "dictionaryForm": "持って来る",
    "teForm": "持って来て",
    "naiForm": "持って来ない",
    "example": "パーティーにワインを持って来ます。(Tôi mang rượu vang đến bữa tiệc)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 82,
    "kanji": "心配します",
    "hiragana": "しんぱいします",
    "meaning": "Lo lắng",
    "group": 3,
    "dictionaryForm": "心配する",
    "teForm": "心配して",
    "naiForm": "心配しない",
    "example": "母はいつも私のことを心配します。(Mẹ tôi luôn lo lắng cho tôi)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 83,
    "kanji": "残業します",
    "hiragana": "ざんぎょうします",
    "meaning": "Làm thêm giờ",
    "group": 3,
    "dictionaryForm": "残業する",
    "teForm": "残業して",
    "naiForm": "残業しない",
    "example": "今日は残業します。(Hôm nay tôi làm thêm giờ)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 84,
    "kanji": "出張します",
    "hiragana": "しゅっちょうします",
    "meaning": "Đi công tác",
    "group": 3,
    "dictionaryForm": "出張する",
    "teForm": "出張して",
    "naiForm": "出張しない",
    "example": "来週大阪へ出張します。(Tuần sau tôi đi công tác Osaka)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 85,
    "kanji": "できます",
    "hiragana": "できます",
    "meaning": "Có thể",
    "group": 2,
    "dictionaryForm": "できる",
    "teForm": "できて",
    "naiForm": "できない",
    "example": "私は日本語ができます。(Tôi có thể nói tiếng Nhật)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 86,
    "kanji": "洗います",
    "hiragana": "あらいます",
    "meaning": "Rửa",
    "group": 1,
    "dictionaryForm": "洗う",
    "teForm": "洗って",
    "naiForm": "洗わない",
    "example": "手を洗います。(Tôi rửa tay)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 87,
    "kanji": "弾きます",
    "hiragana": "ひきます",
    "meaning": "Chơi (nhạc cụ)",
    "group": 1,
    "dictionaryForm": "弾く",
    "teForm": "弾いて",
    "naiForm": "弾かない",
    "example": "ピアノを弾きます。(Tôi chơi piano)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 88,
    "kanji": "歌います",
    "hiragana": "うたいます",
    "meaning": "Hát",
    "group": 1,
    "dictionaryForm": "歌う",
    "teForm": "歌って",
    "naiForm": "歌わない",
    "example": "カラオケで歌います。(Tôi hát ở quán karaoke)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 89,
    "kanji": "集めます",
    "hiragana": "あつめます",
    "meaning": "Sưu tầm",
    "group": 2,
    "dictionaryForm": "集める",
    "teForm": "集めて",
    "naiForm": "集めない",
    "example": "切手を集めています。(Tôi đang sưu tầm tem)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 90,
    "kanji": "捨てます",
    "hiragana": "すてます",
    "meaning": "Vứt",
    "group": 2,
    "dictionaryForm": "捨てる",
    "teForm": "捨てて",
    "naiForm": "捨てない",
    "example": "古い雑誌を捨てます。(Tôi vứt tạp chí cũ)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 91,
    "kanji": "換えます",
    "hiragana": "かえます",
    "meaning": "Đổi",
    "group": 2,
    "dictionaryForm": "換える",
    "teForm": "換えて",
    "naiForm": "換えない",
    "example": "ドルを円に換えます。(Tôi đổi đô la sang yên)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 92,
    "kanji": "運転します",
    "hiragana": "うんてんします",
    "meaning": "Lái xe",
    "group": 3,
    "dictionaryForm": "運転する",
    "teForm": "運転して",
    "naiForm": "運転しない",
    "example": "父は毎日車を運転します。(Bố tôi lái xe hàng ngày)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 93,
    "kanji": "予約します",
    "hiragana": "よやくします",
    "meaning": "Đặt trước",
    "group": 3,
    "dictionaryForm": "予約する",
    "teForm": "予約して",
    "naiForm": "予約しない",
    "example": "ホテルを予約します。(Tôi đặt trước khách sạn)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 94,
    "kanji": "見学します",
    "hiragana": "けんがくします",
    "meaning": "Tham quan (nhà máy)",
    "group": 3,
    "dictionaryForm": "見学する",
    "teForm": "見学して",
    "naiForm": "見学しない",
    "example": "工場を見学します。(Tôi tham quan nhà máy)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 95,
    "kanji": "登ります",
    "hiragana": "のぼります",
    "meaning": "Leo (núi)",
    "group": 1,
    "dictionaryForm": "登る",
    "teForm": "登って",
    "naiForm": "登らない",
    "example": "富士山に登ります。(Tôi leo núi Phú Sĩ)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 96,
    "kanji": "泊まります",
    "hiragana": "とまります",
    "meaning": "Trọ lại",
    "group": 1,
    "dictionaryForm": "泊まる",
    "teForm": "泊まって",
    "naiForm": "泊まらない",
    "example": "ホテルに泊まります。(Tôi trọ lại ở khách sạn)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 97,
    "kanji": "掃除します",
    "hiragana": "そうじします",
    "meaning": "Dọn dẹp",
    "group": 3,
    "dictionaryForm": "掃除する",
    "teForm": "掃除して",
    "naiForm": "掃除しない",
    "example": "部屋を掃除します。(Tôi dọn dẹp phòng)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 98,
    "kanji": "洗濯します",
    "hiragana": "せんたくします",
    "meaning": "Giặt",
    "group": 3,
    "dictionaryForm": "洗濯する",
    "teForm": "洗濯して",
    "naiForm": "洗濯しない",
    "example": "服を洗濯します。(Tôi giặt quần áo)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 99,
    "kanji": "なります",
    "hiragana": "なります",
    "meaning": "Trở nên",
    "group": 1,
    "dictionaryForm": "なる",
    "teForm": "なって",
    "naiForm": "ならない",
    "example": "医者になりたいです。(Tôi muốn trở thành bác sĩ)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 100,
    "kanji": "要ります",
    "hiragana": "いります",
    "meaning": "Cần",
    "group": 1,
    "dictionaryForm": "要る",
    "teForm": "要って",
    "naiForm": "要らない",
    "example": "ビザが要ります。(Tôi cần visa)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 101,
    "kanji": "調べます",
    "hiragana": "しらべます",
    "meaning": "Tìm hiểu, điều tra",
    "group": 2,
    "dictionaryForm": "調べる",
    "teForm": "調べて",
    "naiForm": "調べない",
    "example": "インターネットで調べます。(Tôi tìm hiểu trên internet)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 102,
    "kanji": "修理します",
    "hiragana": "しゅうりします",
    "meaning": "Sửa chữa",
    "group": 3,
    "dictionaryForm": "修理する",
    "teForm": "修理して",
    "naiForm": "修理しない",
    "example": "時計を修理します。(Tôi sửa đồng hồ)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 103,
    "kanji": "思います",
    "hiragana": "おもいます",
    "meaning": "Nghĩ",
    "group": 1,
    "dictionaryForm": "思う",
    "teForm": "思って",
    "naiForm": "思わない",
    "example": "明日は雨が降ると思います。(Tôi nghĩ ngày mai trời sẽ mưa)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 104,
    "kanji": "言います",
    "hiragana": "いいます",
    "meaning": "Nói",
    "group": 1,
    "dictionaryForm": "言う",
    "teForm": "言って",
    "naiForm": "言わない",
    "example": "先生は「頑張ってください」と言いました。(Thầy giáo đã nói \"Hãy cố gắng lên\")",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 105,
    "kanji": "勝ちます",
    "hiragana": "かちます",
    "meaning": "Thắng",
    "group": 1,
    "dictionaryForm": "勝つ",
    "teForm": "勝って",
    "naiForm": "勝たない",
    "example": "試合に勝ちました。(Tôi đã thắng trận đấu)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 106,
    "kanji": "負けます",
    "hiragana": "まけます",
    "meaning": "Thua",
    "group": 2,
    "dictionaryForm": "負ける",
    "teForm": "負けて",
    "naiForm": "負けない",
    "example": "ゲームに負けました。(Tôi đã thua game)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 107,
    "kanji": "役に立ちます",
    "hiragana": "やくにたちます",
    "meaning": "Có ích",
    "group": 1,
    "dictionaryForm": "役に立つ",
    "teForm": "役に立って",
    "naiForm": "役に立たない",
    "example": "この辞書はとても役に立ちます。(Quyển từ điển này rất có ích)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 108,
    "kanji": "動きます",
    "hiragana": "うごきます",
    "meaning": "Chuyển động",
    "group": 1,
    "dictionaryForm": "動く",
    "teForm": "動いて",
    "naiForm": "動かない",
    "example": "時計が動きません。(Cái đồng hồ không chạy)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 109,
    "kanji": "やめます",
    "hiragana": "やめます",
    "meaning": "Bỏ, thôi (việc)",
    "group": 2,
    "dictionaryForm": "やめる",
    "teForm": "やめて",
    "naiForm": "やめない",
    "example": "会社をやめます。(Tôi thôi việc ở công ty)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 110,
    "kanji": "留学します",
    "hiragana": "りゅうがくします",
    "meaning": "Du học",
    "group": 3,
    "dictionaryForm": "留学する",
    "teForm": "留学して",
    "naiForm": "留学しない",
    "example": "日本へ留学します。(Tôi đi du học Nhật Bản)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 111,
    "kanji": "着ます",
    "hiragana": "きます",
    "meaning": "Mặc (áo)",
    "group": 2,
    "dictionaryForm": "着る",
    "teForm": "着て",
    "naiForm": "着ない",
    "example": "シャツを着ます。(Tôi mặc áo sơ mi)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 112,
    "kanji": "はきます",
    "hiragana": "はきます",
    "meaning": "Mặc, Đi (quần, giày)",
    "group": 1,
    "dictionaryForm": "はく",
    "teForm": "はいて",
    "naiForm": "はかない",
    "example": "ズボンをはきます。(Tôi mặc quần)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 113,
    "kanji": "かぶります",
    "hiragana": "かぶります",
    "meaning": "Đội (mũ)",
    "group": 1,
    "dictionaryForm": "かぶる",
    "teForm": "かぶって",
    "naiForm": "かぶらない",
    "example": "帽子をかぶります。(Tôi đội mũ)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 114,
    "kanji": "かけます",
    "hiragana": "かけます",
    "meaning": "Đeo (kính)",
    "group": 2,
    "dictionaryForm": "かける",
    "teForm": "かけて",
    "naiForm": "かけない",
    "example": "眼鏡をかけます。(Tôi đeo kính)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 115,
    "kanji": "生まれます",
    "hiragana": "うまれます",
    "meaning": "Sinh ra",
    "group": 2,
    "dictionaryForm": "生まれる",
    "teForm": "生まれて",
    "naiForm": "生まれない",
    "example": "私は1990年に生まれました。(Tôi sinh năm 1990)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 116,
    "kanji": "回します",
    "hiragana": "まわします",
    "meaning": "Vặn, Xoay",
    "group": 1,
    "dictionaryForm": "回す",
    "teForm": "回して",
    "naiForm": "回さない",
    "example": "つまみを回します。(Tôi vặn núm)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 117,
    "kanji": "引きます",
    "hiragana": "ひきます",
    "meaning": "Kéo",
    "group": 1,
    "dictionaryForm": "引く",
    "teForm": "引いて",
    "naiForm": "引かない",
    "example": "ドアを引きます。(Tôi kéo cửa)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 118,
    "kanji": "変えます",
    "hiragana": "かえます",
    "meaning": "Thay đổi",
    "group": 2,
    "dictionaryForm": "変える",
    "teForm": "変えて",
    "naiForm": "変えない",
    "example": "予定を変えます。(Tôi thay đổi kế hoạch)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 119,
    "kanji": "歩きます",
    "hiragana": "あるきます",
    "meaning": "Đi bộ",
    "group": 1,
    "dictionaryForm": "歩く",
    "teForm": "歩いて",
    "naiForm": "歩かない",
    "example": "駅まで歩きます。(Tôi đi bộ đến ga)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 120,
    "kanji": "渡ります",
    "hiragana": "わたります",
    "meaning": "Qua (cầu, đường)",
    "group": 1,
    "dictionaryForm": "渡る",
    "teForm": "渡って",
    "naiForm": "渡らない",
    "example": "橋を渡ります。(Tôi qua cầu)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 121,
    "kanji": "曲がります",
    "hiragana": "まがります",
    "meaning": "Rẽ, quẹo",
    "group": 1,
    "dictionaryForm": "曲がる",
    "teForm": "曲がって",
    "naiForm": "曲がらない",
    "example": "角を右へ曲がります。(Tôi rẽ phải ở góc đường)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 122,
    "kanji": "くれます",
    "hiragana": "くれます",
    "meaning": "Cho, tặng (tôi)",
    "group": 2,
    "dictionaryForm": "くれる",
    "teForm": "くれて",
    "naiForm": "くれない",
    "example": "友達がプレゼントをくれました。(Bạn tôi đã tặng quà cho tôi)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 123,
    "kanji": "直します",
    "hiragana": "なおします",
    "meaning": "Sửa, chữa",
    "group": 1,
    "dictionaryForm": "直す",
    "teForm": "直して",
    "naiForm": "直さない",
    "example": "自転車を直します。(Tôi sửa xe đạp)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 124,
    "kanji": "連れて行きます",
    "hiragana": "つれていきます",
    "meaning": "Dẫn đi",
    "group": 1,
    "dictionaryForm": "連れて行く",
    "teForm": "連れて行って",
    "naiForm": "連れて行かない",
    "example": "子供を公園へ連れて行きます。(Tôi dẫn con đi công viên)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 125,
    "kanji": "連れて来ます",
    "hiragana": "つれてきます",
    "meaning": "Dẫn đến",
    "group": 3,
    "dictionaryForm": "連れて来る",
    "teForm": "連れて来て",
    "naiForm": "連れて来ない",
    "example": "友達をパーティーに連れて来ます。(Tôi dẫn bạn đến bữa tiệc)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 126,
    "kanji": "紹介します",
    "hiragana": "しょうかいします",
    "meaning": "Giới thiệu",
    "group": 3,
    "dictionaryForm": "紹介する",
    "teForm": "紹介して",
    "naiForm": "紹介しない",
    "example": "新しい先生を紹介します。(Tôi giới thiệu giáo viên mới)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 127,
    "kanji": "案内します",
    "hiragana": "あんないします",
    "meaning": "Hướng dẫn",
    "group": 3,
    "dictionaryForm": "案内する",
    "teForm": "案内して",
    "naiForm": "案内しない",
    "example": "町を案内します。(Tôi hướng dẫn (tham quan) thành phố)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 128,
    "kanji": "説明します",
    "hiragana": "せつめいします",
    "meaning": "Giải thích",
    "group": 3,
    "dictionaryForm": "説明する",
    "teForm": "説明して",
    "naiForm": "説明しない",
    "example": "文法を説明します。(Tôi giải thích ngữ pháp)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 129,
    "kanji": "考えます",
    "hiragana": "かんがえます",
    "meaning": "Suy nghĩ",
    "group": 2,
    "dictionaryForm": "考える",
    "teForm": "考えて",
    "naiForm": "考えない",
    "example": "将来について考えます。(Tôi suy nghĩ về tương lai)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  },
  {
    "id": 130,
    "kanji": "着きます",
    "hiragana": "つきます",
    "meaning": "Đến nơi",
    "group": 1,
    "dictionaryForm": "着く",
    "teForm": "着いて",
    "naiForm": "着かない",
    "example": "駅に着きました。(Tôi đã đến ga)",
    "progress": { "hiragana": 0, "kanji": 0 },
    "note": ""
  }
];
